export enum WIDTHS {
	XS = 320,
	S = 480,
	M = 768,
	L = 992,
	XL = 1200
}

export enum FONT_SIZES {
	H1 = 4,
	H2 = 3.5,
	H3 = 2.8,
	P = 1.8,
}

export enum LINE_HEIGHTS {
	DEFAULT = 1.5,
	PROSE = 1.7
}

export enum VERTICAL_RHYTHMS {
	H1 = FONT_SIZES.H1 * LINE_HEIGHTS.DEFAULT,
	H2 = FONT_SIZES.H2 * LINE_HEIGHTS.DEFAULT,
	H3 = FONT_SIZES.H3 * LINE_HEIGHTS.DEFAULT,
	P = FONT_SIZES.P * LINE_HEIGHTS.PROSE,
}
