name: CI

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - name: Build
      env:
        LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}
      run: |
        printf "GATSBY_LAST_FM_API_KEY=${{secrets.LAST_FM_API_KEY}}\nDISCOGS_TOKEN=${{secrets.DISCOGS_TOKEN}}" >> .env
        npm install -g yarn
        yarn install
        mkdir src/pages/blog
        yarn run build --if-present
    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        AWS_DEFAULT_REGION: ap-southeast-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      run: node ./scripts/deploy.js
    - name: Purge cache
      uses: 3stacks/cloudflare-purge-cache-action@v1.0.6
      with:
        authToken: ${{ secrets.CLOUDFLARE_AUTH_TOKEN }}
        siteName: lukeboyle.com
        authEmail: me@lukeboyle.com
